services:
  stroom-validator:
    image: public.ecr.aws/g3y5i1b4/stroom-validator:latest
    container_name: stroom-validator
    ports:
      - "4444:4444"
    command:
      - "--http.address=0.0.0.0:8080"
      - "--eth.rpc-url=${ETHEREUM_RPC_URL:?error}"
      - "--node.approval-threshold=${APPROVAL_THRESHOLD:?error}"
      - "--node.listen-address=0.0.0.0:4444"
      - "--node.state-storage-dir=/data/stroom"
      - "--wallet.appdata=/data/btcwallet"
      - "--bitcoin.host=${BITCOIN_RPC_HOST:?error}"
      - "--bitcoin.user=${BITCOIN_RPC_USER:?error}"
      - "--bitcoin.password=${BITCOIN_RPC_PASSWORD:?error}"
      - "--bitcoin.vendor=bitcoind"
      - "--bitcoin.chain=${BITCOIN_CHAIN:?error}"
      - "--eth.watch.finalization-depth=3"
      - "--bitcoin.watch.finalization-depth=3"
      - "--eth.watch.start-height=${ETHEREUM_START_HEIGHT:?error}"
      - "--bitcoin.watch.start-height=${BITCOIN_START_HEIGHT:?error}"
      - "--node.private-key=${NODE_PRIVATE_KEY:?error}"
      - "--eth.contract-address.stbtc=${STBTC_CONTRACT:-0xa8f5f8a159e3270453a3411986e2c12415365a5a}"
      - "--eth.contract-address.bstbtc=${BSTBTC_CONTRACT:-0xb6b8c974d5aeff82fba14489a353839e7a93b2b3}"
      - "--eth.contract-address.validator-registry=${VALIDATOR_REGISTRY_CONTRACT:-0x602f76f4e6b585f550b21706e93a7a674ce5ea00}"
      - "--eth.contract-address.user-activator=${USER_ACTIVATOR_CONTRACT:-0x2a998b721014a3453c29e56e7a0f6282e920bb42}"
      - "--app.start-timeout=30m"
      - "--node.frost-key-session-timeout=5s"
      - "--node.ethereum-network-name=sepolia"
      - "--node.bitcoin-network-name=${BITCOIN_CHAIN:-testnet4}"
      # ### NODE PEER ADDRESSES here ###
      # - "--node.peer-addresses=''"
      # - "--node.peer-addresses=''"
      # ### ###
    volumes:
      - ./testnet-data:/data

