services:
  stroom-validator:
    image: public.ecr.aws/g3y5i1b4/stroom-validator:latest
    labels:
      - "network.stroom.stack=stroom"
      - "network.stroom.monitoring-enable=true"
    container_name: stroom-validator
    ports:
      - "4444:4444"
    command:
      - "--http.address=0.0.0.0:8080"
      - "--eth.rpc-url=${ETHEREUM_RPC_URL:-https://ethereum.testnetrvp.stroom.ninja:443}"
      - "--node.approval-threshold=${APPROVAL_THRESHOLD}"
      - "--node.listen-address=0.0.0.0:4444"
      - "--node.state-storage-dir=/data/stroom"
      - "--wallet.appdata=/data/btcwallet"
      - "--bitcoin.host=${BITCOIN_RPC_HOST:-bitcoin.testnetrvp.stroom.ninja:48332}"
      - "--bitcoin.vendor=bitcoind"
      - "--bitcoin.chain=${BITCOIN_CHAIN:-testnet4}"
      - "--eth.watch.finalization-depth=3"
      - "--bitcoin.watch.finalization-depth=3"
      - "--eth.watch.start-height=${ETHEREUM_START_HIGHT:?error}"
      - "--bitcoin.watch.start-height=${BITCOIN_START_HIGHT:?error}"
      - "--node.private-key=${NODE_PRIVATE_KEY:?error}"
      - "--eth.contract-address.stbtc=${STBTC_CONTRACT:-0xa8f5f8a159e3270453a3411986e2c12415365a5a}"
      - "--eth.contract-address.bstbtc=${BSTBTC_CONTRACT:-0xb6b8c974d5aeff82fba14489a353839e7a93b2b3}"
      - "--eth.contract-address.validator-registry=${VALIDATOR_REGISTRY_CONTRACT:-0x602f76f4e6b585f550b21706e93a7a674ce5ea00}"
      - "--eth.contract-address.user-activator=${USER_ACTIVATOR_CONTRACT:-0x2a998b721014a3453c29e56e7a0f6282e920bb42}"
      - "--app.start-timeout=20m"
      - "--node.frost-key-session-timeout=2s"
      - "--node.ethereum-network-name=sepolia"
      - "--node.bitcoin-network-name=${BITCOIN_CHAIN:-testnet4}"
      # ### NODE PEER ADDRESSES here ###
      # - "--node.peer-addresses=''"
      # - "--node.peer-addresses=''"
      # ### ###
    environment:
      - APP_BITCOIN_PRC_PASSWORD=${BITCOIND_RPCPASSWORD:?error}
      - APP_BITCOIN_RPC_USER=${BITCOIND_RPCUSER:?error}
    volumes:
      - ./testnet-data:/data
    networks:
      - stroom
  telegraf:
    image: public.ecr.aws/g3y5i1b4/validator-telegraf:latest
    labels:
      - "network.stroom.stack=support"
    container_name: telegraf
    ports: []
    environment:
      AWS_REGION: "${AWS_REGION:-eu-north-1}"
      AWS_ROLE_ARN: "${AWS_ROLE_ARN:?error}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:?error}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:?error}"
      TENANT: "${TENANT:?error}"
      DOCKER_HOST: "tcp://docker-socket-proxy:2375"
    depends_on:
      - docker-socket-proxy
    networks:
      - stroom
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker-socket-proxy
    environment:
      CONTAINERS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2375:2375"
    networks:
      - stroom
networks:
  stroom:
