services:
  stroom-validator:
    image: public.ecr.aws/g3y5i1b4/stroom-validator:latest
    container_name: stroom-validator
    pull_policy: always
    ports:
      - "4444:4444"
      - "8080:8080"
      - "8081:8081"
    command:
      - "--http.address=0.0.0.0:8080"
      - "--eth.rpc-url=${ETHEREUM_RPC_URL:?error}"
      - "--node.approval-threshold=${APPROVAL_THRESHOLD:?error}"
      - "--node.listen-address=0.0.0.0:4444"
      - "--node.state-storage-dir=/data/stroom"
      - "--wallet.appdata=/data/btcwallet"
      - "--bitcoin.host=${BITCOIN_RPC_HOST:?error}"
      - "--bitcoin.user=${BITCOIN_RPC_USER:?error}"
      - "--bitcoin.password=${BITCOIN_RPC_PASSWORD:?error}"
      - "--bitcoin.vendor=bitcoind"
      - "--bitcoin.chain=${BITCOIN_CHAIN:?error}"
      - "--eth.watch.finalization-depth=3"
      - "--bitcoin.watch.finalization-depth=3"
      - "--eth.watch.start-height=${ETHEREUM_START_HEIGHT:?error}"
      - "--bitcoin.watch.start-height=${BITCOIN_START_HEIGHT:?error}"
      - "--node.private-key=${NODE_PRIVATE_KEY:?error}"
      - "--eth.contract-address.stbtc=${STBTC_CONTRACT:-0x02a416f9ad9297dde0bb98f0cdb8b7ad5fbb0c36}"
      - "--eth.contract-address.bstbtc=${BSTBTC_CONTRACT:-0xf0ccae6d128c91d338f3910412be5ba7d5dcd039}"
      - "--eth.contract-address.validator-registry=${VALIDATOR_REGISTRY_CONTRACT:-0x4bc2e3026ba0c088501a705f37fb34e5d63c06b8}"
      - "--eth.contract-address.user-activator=${USER_ACTIVATOR_CONTRACT:-0x29c9d9b032db66fe4b4d4ec9071262714744b448}"
      - "--app.start-timeout=30m"
      - "--node.frost-key-session-timeout=5s"
      - "--node.ethereum-network-name=sepolia"
      - "--node.bitcoin-network-name=${BITCOIN_CHAIN:-testnet4}"
      # ### NODE PEER ADDRESSES here ###
      # - "--node.peer-addresses=''"
      # - "--node.peer-addresses=''"
      # ### ###
    volumes:
      - ./testnet-data:/data

