services:
  stroom-validator:
    image: public.ecr.aws/g3y5i1b4/stroom-validator:${APP_VERSION:?error}
    labels:
      - "network.stroom.stack=stroom"
      - "network.stroom.monitoring-enable=true"
    container_name: stroom-validator
    pull_policy: always
    ports:
      - "4444:4444"
      - "8080:8080"
      - "127.0.0.1:8081:8081"
    command:
      - "--http.address=0.0.0.0:8080"
      - "--eth.rpc-url=${ETHEREUM_RPC_URL:?error}"
      - "--node.approval-threshold=${APPROVAL_THRESHOLD:?error}"
      - "--node.listen-address=0.0.0.0:4444"
      - "--node.state-storage-dir=/data/stroom"
      - "--wallet.appdata=/data/btcwallet"
      - "--bitcoin.host=${BITCOIN_RPC_HOST:?error}"
      - "--bitcoin.user=${BITCOIN_RPC_USER:?error}"
      - "--bitcoin.password=${BITCOIN_RPC_PASSWORD:?error}"
      - "--bitcoin.vendor=bitcoind"
      - "--bitcoin.chain=${BITCOIN_CHAIN:?error}"
      - "--eth.watch.finalization-depth=3"
      - "--bitcoin.watch.finalization-depth=3"
      - "--eth.watch.start-height=${ETHEREUM_START_HEIGHT:?error}"
      - "--bitcoin.watch.start-height=${BITCOIN_START_HEIGHT:?error}"
      - "--node.private-key=${NODE_PRIVATE_KEY:?error}"
      - "--eth.contract-address.stbtc=${STBTC_CONTRACT:-0x02a416f9ad9297dde0bb98f0cdb8b7ad5fbb0c36}"
      - "--eth.contract-address.bstbtc=${BSTBTC_CONTRACT:-0xf0ccae6d128c91d338f3910412be5ba7d5dcd039}"
      - "--eth.contract-address.validator-registry=${VALIDATOR_REGISTRY_CONTRACT:-0x4bc2e3026ba0c088501a705f37fb34e5d63c06b8}"
      - "--eth.contract-address.user-activator=${USER_ACTIVATOR_CONTRACT:-0x29c9d9b032db66fe4b4d4ec9071262714744b448}"
      - "--app.start-timeout=30m"
      - "--node.frost-key-session-timeout=5s"
      - "--node.ethereum-network-name=sepolia"
      - "--node.bitcoin-network-name=${BITCOIN_CHAIN:-testnet4}"
      - "--app.log-level=${LOG_LEVEL:?error}"
      # ### NODE PEER ADDRESSES here ###
      # - "--node.peer-addresses=''"
      # - "--node.peer-addresses=''"
      # ### ###
    volumes:
      - testnet-data:/data
    networks:
      - stroom
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  support.telegraf:
    image: public.ecr.aws/g3y5i1b4/validator-telegraf:latest
    labels:
      - "network.stroom.stack=support"
    container_name: support-telegraf
    ports: []
    env_file:
      - ./.env
    environment:
      AWS_REGION: "${AWS_REGION:-eu-north-1}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:?error}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:?error}"
      AWS_ROLE_ARN: "${AWS_ROLE_ARN:?error}"
      TENANT: "${TENANT:?error}"
      DOCKER_HOST: "tcp://support-docker-socket-proxy:2375"
      LOG_GROUP_NAME: "${LOG_GROUP_NAME:?error}"
    depends_on:
      - support-docker-socket-proxy
    networks:
      - stroom
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
  support-docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: support-docker-socket-proxy
    environment:
      CONTAINERS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2375:2375"
    networks:
      - stroom
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
networks:
  stroom:

volumes:
  testnet-data:
